package cs451.links;

import cs451.messages.Message;

import javax.swing.text.html.Option;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

public class PerfectLink implements Link, Runnable{
    FairLossLink fairLossLink;
    Map<Tuple<Integer, Long>, Message> buffer;

    public PerfectLink(int port) {
        fairLossLink = new FairLossLink(port);
        buffer = new HashMap<Tuple<Integer, Long>, Message>();
    }

    public void run() {
        while (true) {
            deliver();
            //TODO resend a message only if it timed out (one timer per message)
            buffer.forEach((id,message) -> fairLossLink.send(message));
            try {
                Thread.sleep(300);
            } catch (InterruptedException e) {
                System.out.print("Thread interrupted");
                e.printStackTrace();
            }
        }
    }

    public void send(Message message) {
        if (message.getContent().equals("ack")) {
            //TODO improve
            return;
        }
        buffer.put(new Tuple(message.getSender().getId(), message.getId()), message);
    }

    public Optional<Message> deliver() {
        Optional<Message> optMessage = fairLossLink.deliver();
        if (optMessage.isPresent()) {
            Message message = optMessage.get();
            //TODO : add an atribute "isAck" in Message or Inheritance to avoid random conversion
            if (message.getContent().equals("ack")) {
                buffer.remove(new Tuple<Integer, Long>(message.getDest().getId(), message.getId()));
                return Optional.empty();
            } else {
                fairLossLink.send(new Message(message.getId(), "ack", message.getDest(), message.getSender()));
                return optMessage;
            }
        }
        return Optional.empty();
    }

    //First part of this class comes from StackOverflow, equals and hashcode were generated by my IDE
    public class Tuple<X, Y> {
        public final X x;
        public final Y y;
        public Tuple(X x, Y y) {
            this.x = x;
            this.y = y;
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            Tuple<?, ?> tuple = (Tuple<?, ?>) o;
            return Objects.equals(x, tuple.x) &&
                    Objects.equals(y, tuple.y);
        }

        @Override
        public int hashCode() {
            return Objects.hash(x, y);
        }
    }
}
