package cs451.links;

import cs451.Receiver;
import cs451.messages.Message;

import java.util.*;

public class PerfectLink implements Runnable, Receiver {
    private final FairLossLink fairLossLink;
    private final Map<Tuple<Integer, Long>, Message> sendBuffer;
    private final Set<Message> receivedMessages;
    private final Receiver receiver;

    public PerfectLink(Receiver receiver, int port) {
        this.receiver = receiver;
        fairLossLink = new FairLossLink(this, port);
        sendBuffer = new HashMap<Tuple<Integer, Long>, Message>();
        receivedMessages = new HashSet<>();
        Thread fairLossThread = new Thread(fairLossLink);
        fairLossThread.start();
    }

    @Override
    public void run() {
        while (true) {
            //TODO resend a message only if it timed out (one timer per message)
            sendBuffer.forEach((id, message) -> fairLossLink.send(message));
            try {
                Thread.sleep(150);
            } catch (InterruptedException e) {
                System.out.print("Thread interrupted");
                e.printStackTrace();
            }
        }
    }

    public void send(Message message) {
        if (message.getContent().equals("ack")) {
            //TODO improve
            return;
        }
        sendBuffer.put(new Tuple(message.getDest().getId(), message.getId()), message);
    }

    @Override
    public void deliver(Message message) {
        //TODO : add an atribute "isAck" in Message or Inheritance to avoid random conversion
        if (message.getContent().equals("ack")) {
            sendBuffer.remove(new Tuple<Integer, Long>(message.getSender().getId(), message.getId()));
        } else if (receivedMessages.contains(message)){
            System.out.println("###DEBUG message "+message.getContent() + "already delivered");
            System.out.flush();
        } else {
            fairLossLink.send(new Message(message.getId(), "ack", message.getDest(), message.getSender()));
            receivedMessages.add(message);
            receiver.deliver(message);
        }
    }

    //First part of this class comes from StackOverflow, equals and hashcode were generated by my IDE
    public class Tuple<X, Y> {
        public final X x;
        public final Y y;
        public Tuple(X x, Y y) {
            this.x = x;
            this.y = y;
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            Tuple<?, ?> tuple = (Tuple<?, ?>) o;
            return Objects.equals(x, tuple.x) &&
                    Objects.equals(y, tuple.y);
        }

        @Override
        public int hashCode() {
            return Objects.hash(x, y);
        }
    }
}
